### PR TITLE
issue-8 - update to Spark 2

### LINKED ISSUE #7: Date fields cause java cast error
If any of the indexed metadata fields are set up as datetime, when trying to retrieve the fields via Zeppelin a cast error is generated:
```
java.lang.ClassCastException: org.joda.time.Instant cannot be cast to java.sql.Timestamp
```
Dataframe:
`
df: org.apache.spark.sql.DataFrame = [domain-name: string, site: string, meas-start-datetime: timestamp, meas-end-datetime: timestamp, meas-strm-name: string, meas-strm-id: string, ObjectName: string, LastModified: timestamp, Owner: string, Size: int, CreateTime: timestamp, LastModified: timestamp, Owner: string, ContentType: string, Etag: string, Size: int, CreateTime: timestamp, Expiration: timestamp, ContentEncoding: string, Expires: timestamp, Retention: int, Namespace: string, ObjectName: string, Key: string]
`

Query:
```
%sql
SELECT* FROM ECS WHERE `domain-name` = "D03" LIMIT 10
```
Error:
```
java.lang.ClassCastException: org.joda.time.Instant cannot be cast to java.sql.Timestamp
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$TimestampConverter$.toCatalystImpl(CatalystTypeConverters.scala:313)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:97)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$2.apply(CatalystTypeConverters.scala:401)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:59)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:56)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:308)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$5.apply(SparkPlan.scala:212)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

### LINKED ISSUE #8: Update to Spark 2.x

### PR DESCRIPTION
**Pull request by EronWright**
Closes #8 
Closes #7 

- update to Spark 2.x
- replace sbt with gradle build
- shaded jar file to eliminate conflicts
- integration tests
- moved datasource class to separate file
- fix timestamp handling
- ensure shutdown of execution context for content download
- switch from urlconnection to apache http
- enable wire logging in tests

TODO: update README.md

### CODE REVIEW

**Comment by EronWright** [comment]
@twincitiesguy please give this a try like so:

```
./gradlew clean intTest -Ps3.endpoint=http://10.1.83.51:9020 -Ps3.accessKeyId=ben -Ps3.secretAccessKey=<secretkey>
```

**Comment by brokenjacobs** [comment]
I don't have an easy way to test this change without an updated docker container. I lack the knowledge to get this running. I got it compiled and a local copy of zeppelin 0.7.1 running, but the %dep line fails org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact com.emc.ecs:spark-ecs-s3_2.11:jar:1.4-SNAPSHOT in central (http://repo1.maven.org/maven2/)

Presumeably because I need a local maven repo with these artifacts in them?

**Comment by EronWright** [comment]
@brokenjacobs we'll get the library published to Maven Central soon, then you can use it in Zeppelin without issue.   That said, the `./gradlew publishShadowPublicationToMavenLocal` command does install the library to local Maven repository (which is located at `~/.m2/repository`).   I believe that Zeppelin will pick up the library from there.

**Comment by brokenjacobs** [comment]
when checking out this issue branch I can't compile the project:
[info]   Compilation completed in 7.11 s
[error] /Users/sjacobs/work/zeppelin/spark-ecs-s3/src/main/scala/com/emc/ecs/spark/sql/sources/s3/datasource.scala:6: object apache is not a member of package org
[error] /Users/sjacobs/work/zeppelin/spark-ecs-s3/src/main/scala/com/emc/ecs/spark/sql/sources/s3/datasource.scala:6: object apache is not a member of package org
[error] import org.apache.spark.sql.SQLContext
[error] import org.apache.spark.sql.SQLContext

**Comment by brokenjacobs** [comment]
We got it working with using gradle instead of sbf to build. No more exceptions, and the dates appear properly. Although we did get a deprecation warning on registering the dataframe. See attached:
image

**Comment by EronWright** [comment]
@brokenjacobs great to hear!    The deprecation warning is related to the use of `registerTempTable`, which is deprecated in Spark 2.0 in favor of `createOrReplaceTempView`.

**Pull request merged**
